package employeetardiness;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author AndrewYang
 */
public class employeeTardinessGUI extends javax.swing.JFrame {

    /**
     * Creates new form employeeTardinessGUI
     */
    public employeeTardinessGUI() {
        initComponents();

    }

//    
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEmployeeMenu = new javax.swing.JFrame();
        newEmployeePanel = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeePositionLabel = new javax.swing.JLabel();
        newEmployeeNameField = new javax.swing.JTextField();
        newEmployeeIDField = new javax.swing.JTextField();
        newEmployeeBack = new javax.swing.JButton();
        newEmployeeContinue = new javax.swing.JButton();
        removeEmployeeMenu = new javax.swing.JFrame();
        removeEmployeePanel = new javax.swing.JPanel();
        removeEmployeeNameLabel = new javax.swing.JLabel();
        removeEmployeeNameField = new javax.swing.JTextField();
        removeEmployeeBack = new javax.swing.JButton();
        removeEmployeeContinue = new javax.swing.JButton();
        removeEmployeeIDLabel = new javax.swing.JLabel();
        removeEmployeeIDField = new javax.swing.JTextField();
        removeEmployeeWarning = new javax.swing.JFrame();
        removeWarningPanel = new javax.swing.JPanel();
        warningText1 = new javax.swing.JLabel();
        warningText2 = new javax.swing.JLabel();
        warningBackButton = new javax.swing.JButton();
        warningContinueButton = new javax.swing.JButton();
        removeEmployeeSuccess = new javax.swing.JFrame();
        removeSuccessPanel = new javax.swing.JPanel();
        removeSuccessText = new javax.swing.JLabel();
        removeFinishButton = new javax.swing.JButton();
        tardinessDisplay = new javax.swing.JFrame();
        tardinessDisplayPanel = new javax.swing.JPanel();
        loginText = new javax.swing.JLabel();
        logoutText = new javax.swing.JLabel();
        tardinessTodayText = new javax.swing.JLabel();
        loginTime = new javax.swing.JLabel();
        logoutTime = new javax.swing.JLabel();
        tardinessTodayTime = new javax.swing.JLabel();
        tardinessDisplayDone = new javax.swing.JButton();
        timeAtWorkLabel = new javax.swing.JLabel();
        totalTime = new javax.swing.JLabel();
        tardinessMenu = new javax.swing.JFrame();
        employeeTardinessMenu = new javax.swing.JPanel();
        employeeTardinessName = new javax.swing.JLabel();
        employeeTardinessNameField = new javax.swing.JTextField();
        employeeTardinessBack = new javax.swing.JButton();
        employeeTardinessContinue = new javax.swing.JButton();
        employeeTardinessID = new javax.swing.JLabel();
        employeeTardinessIDField = new javax.swing.JTextField();
        tardinessNoEmployee = new javax.swing.JFrame();
        noEmployeePanel = new javax.swing.JPanel();
        noEmployeeText = new javax.swing.JLabel();
        noEmployeeConfirmButton = new javax.swing.JButton();
        addEmployeeSuccess = new javax.swing.JFrame();
        addEmployeeSuccessPanel = new javax.swing.JPanel();
        addEmployeeSuccessText = new javax.swing.JLabel();
        addEmployeeSuccessButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        helpPage = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        helpPageDone = new javax.swing.JButton();
        mainMenuPanel = new javax.swing.JPanel();
        newEmployeeButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        checkTardinessButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        newEmployeePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        newEmployeePanel.setToolTipText("");

        employeeNameLabel.setText("Name:");

        employeePositionLabel.setText("ID:");

        newEmployeeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeNameFieldActionPerformed(evt);
            }
        });

        newEmployeeIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeIDFieldActionPerformed(evt);
            }
        });

        newEmployeeBack.setText("Back");
        newEmployeeBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newEmployeeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeBackActionPerformed(evt);
            }
        });

        newEmployeeContinue.setForeground(new java.awt.Color(0, 0, 255));
        newEmployeeContinue.setText("Continue");
        newEmployeeContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newEmployeeContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newEmployeePanelLayout = new javax.swing.GroupLayout(newEmployeePanel);
        newEmployeePanel.setLayout(newEmployeePanelLayout);
        newEmployeePanelLayout.setHorizontalGroup(
            newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addComponent(newEmployeeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newEmployeeContinue, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addGroup(newEmployeePanelLayout.createSequentialGroup()
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeNameLabel)
                            .addComponent(employeePositionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newEmployeeNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(newEmployeeIDField))))
                .addContainerGap())
        );
        newEmployeePanelLayout.setVerticalGroup(
            newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNameLabel)
                    .addComponent(newEmployeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePositionLabel)
                    .addComponent(newEmployeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(newEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEmployeeBack)
                    .addComponent(newEmployeeContinue))
                .addContainerGap())
        );

        javax.swing.GroupLayout newEmployeeMenuLayout = new javax.swing.GroupLayout(newEmployeeMenu.getContentPane());
        newEmployeeMenu.getContentPane().setLayout(newEmployeeMenuLayout);
        newEmployeeMenuLayout.setHorizontalGroup(
            newEmployeeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        newEmployeeMenuLayout.setVerticalGroup(
            newEmployeeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        removeEmployeePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N

        removeEmployeeNameLabel.setText("Employee Name:");

        removeEmployeeBack.setText("Back");
        removeEmployeeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeBackActionPerformed(evt);
            }
        });

        removeEmployeeContinue.setForeground(new java.awt.Color(0, 0, 255));
        removeEmployeeContinue.setText("Continue");
        removeEmployeeContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeContinueActionPerformed(evt);
            }
        });

        removeEmployeeIDLabel.setText("Employee ID:");

        javax.swing.GroupLayout removeEmployeePanelLayout = new javax.swing.GroupLayout(removeEmployeePanel);
        removeEmployeePanel.setLayout(removeEmployeePanelLayout);
        removeEmployeePanelLayout.setHorizontalGroup(
            removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeePanelLayout.createSequentialGroup()
                .addComponent(removeEmployeeBack, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeEmployeeContinue, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
            .addGroup(removeEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeEmployeeNameLabel)
                    .addComponent(removeEmployeeIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeEmployeeNameField)
                    .addComponent(removeEmployeeIDField))
                .addContainerGap())
        );
        removeEmployeePanelLayout.setVerticalGroup(
            removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEmployeeNameLabel)
                    .addComponent(removeEmployeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEmployeeIDLabel)
                    .addComponent(removeEmployeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(removeEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEmployeeBack)
                    .addComponent(removeEmployeeContinue))
                .addContainerGap())
        );

        javax.swing.GroupLayout removeEmployeeMenuLayout = new javax.swing.GroupLayout(removeEmployeeMenu.getContentPane());
        removeEmployeeMenu.getContentPane().setLayout(removeEmployeeMenuLayout);
        removeEmployeeMenuLayout.setHorizontalGroup(
            removeEmployeeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        removeEmployeeMenuLayout.setVerticalGroup(
            removeEmployeeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        removeWarningPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Warning!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        warningText1.setText("You are about to remove an employee permanently from the");

        warningText2.setText("database. Are you sure to continue?");

        warningBackButton.setText("Back");
        warningBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningBackButtonActionPerformed(evt);
            }
        });

        warningContinueButton.setText("Continue");
        warningContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeWarningPanelLayout = new javax.swing.GroupLayout(removeWarningPanel);
        removeWarningPanel.setLayout(removeWarningPanelLayout);
        removeWarningPanelLayout.setHorizontalGroup(
            removeWarningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeWarningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removeWarningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warningText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(removeWarningPanelLayout.createSequentialGroup()
                        .addComponent(warningText2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(removeWarningPanelLayout.createSequentialGroup()
                .addComponent(warningBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningContinueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeWarningPanelLayout.setVerticalGroup(
            removeWarningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeWarningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removeWarningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warningBackButton)
                    .addComponent(warningContinueButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout removeEmployeeWarningLayout = new javax.swing.GroupLayout(removeEmployeeWarning.getContentPane());
        removeEmployeeWarning.getContentPane().setLayout(removeEmployeeWarningLayout);
        removeEmployeeWarningLayout.setHorizontalGroup(
            removeEmployeeWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeWarningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeWarningPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        removeEmployeeWarningLayout.setVerticalGroup(
            removeEmployeeWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeWarningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeWarningPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        removeSuccessPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Success", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N

        removeSuccessText.setText("The employee has been successfully removed.");

        removeFinishButton.setText("Finish");
        removeFinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFinishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeSuccessPanelLayout = new javax.swing.GroupLayout(removeSuccessPanel);
        removeSuccessPanel.setLayout(removeSuccessPanelLayout);
        removeSuccessPanelLayout.setHorizontalGroup(
            removeSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeSuccessText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(removeSuccessPanelLayout.createSequentialGroup()
                .addComponent(removeFinishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        removeSuccessPanelLayout.setVerticalGroup(
            removeSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeSuccessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeFinishButton))
        );

        javax.swing.GroupLayout removeEmployeeSuccessLayout = new javax.swing.GroupLayout(removeEmployeeSuccess.getContentPane());
        removeEmployeeSuccess.getContentPane().setLayout(removeEmployeeSuccessLayout);
        removeEmployeeSuccessLayout.setHorizontalGroup(
            removeEmployeeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeSuccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        removeEmployeeSuccessLayout.setVerticalGroup(
            removeEmployeeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeEmployeeSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeSuccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tardinessDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Tardiness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N

        loginText.setText("Login:");

        logoutText.setText("Logout:");

        tardinessTodayText.setText("Tardiness Today:");

        loginTime.setText("time");

        logoutTime.setText("time");

        tardinessTodayTime.setText("time");

        tardinessDisplayDone.setText("Done");
        tardinessDisplayDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tardinessDisplayDoneActionPerformed(evt);
            }
        });

        timeAtWorkLabel.setText("Time at Work:");

        totalTime.setText("time");

        javax.swing.GroupLayout tardinessDisplayPanelLayout = new javax.swing.GroupLayout(tardinessDisplayPanel);
        tardinessDisplayPanel.setLayout(tardinessDisplayPanelLayout);
        tardinessDisplayPanelLayout.setHorizontalGroup(
            tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tardinessDisplayDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tardinessDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginText)
                    .addComponent(logoutText)
                    .addComponent(tardinessTodayText)
                    .addComponent(timeAtWorkLabel))
                .addGap(54, 54, 54)
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTime)
                    .addComponent(tardinessTodayTime)
                    .addComponent(logoutTime)
                    .addComponent(loginTime))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        tardinessDisplayPanelLayout.setVerticalGroup(
            tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginText)
                    .addComponent(loginTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutText)
                    .addComponent(logoutTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tardinessTodayText)
                    .addComponent(tardinessTodayTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tardinessDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeAtWorkLabel)
                    .addComponent(totalTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tardinessDisplayDone))
        );

        javax.swing.GroupLayout tardinessDisplayLayout = new javax.swing.GroupLayout(tardinessDisplay.getContentPane());
        tardinessDisplay.getContentPane().setLayout(tardinessDisplayLayout);
        tardinessDisplayLayout.setHorizontalGroup(
            tardinessDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tardinessDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tardinessDisplayLayout.setVerticalGroup(
            tardinessDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tardinessDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeeTardinessMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Tardiness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        employeeTardinessMenu.setToolTipText("");

        employeeTardinessName.setText("Name:");

        employeeTardinessNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTardinessNameFieldActionPerformed(evt);
            }
        });

        employeeTardinessBack.setText("Back");
        employeeTardinessBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTardinessBackActionPerformed(evt);
            }
        });

        employeeTardinessContinue.setText("Continue");
        employeeTardinessContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTardinessContinueActionPerformed(evt);
            }
        });

        employeeTardinessID.setText("ID:");

        employeeTardinessIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTardinessIDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeeTardinessMenuLayout = new javax.swing.GroupLayout(employeeTardinessMenu);
        employeeTardinessMenu.setLayout(employeeTardinessMenuLayout);
        employeeTardinessMenuLayout.setHorizontalGroup(
            employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeTardinessMenuLayout.createSequentialGroup()
                .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeTardinessMenuLayout.createSequentialGroup()
                        .addComponent(employeeTardinessBack, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeTardinessContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(employeeTardinessMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeTardinessName)
                            .addComponent(employeeTardinessID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeTardinessNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(employeeTardinessIDField))))
                .addContainerGap())
        );
        employeeTardinessMenuLayout.setVerticalGroup(
            employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeTardinessMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeTardinessName)
                    .addComponent(employeeTardinessNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeTardinessID)
                    .addComponent(employeeTardinessIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(employeeTardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeTardinessBack)
                    .addComponent(employeeTardinessContinue))
                .addContainerGap())
        );

        javax.swing.GroupLayout tardinessMenuLayout = new javax.swing.GroupLayout(tardinessMenu.getContentPane());
        tardinessMenu.getContentPane().setLayout(tardinessMenuLayout);
        tardinessMenuLayout.setHorizontalGroup(
            tardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeTardinessMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tardinessMenuLayout.setVerticalGroup(
            tardinessMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeTardinessMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noEmployeePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Error", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        noEmployeeText.setText("This employee does not exist. Please re-enter a name.");

        noEmployeeConfirmButton.setText("Confirm");
        noEmployeeConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noEmployeeConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout noEmployeePanelLayout = new javax.swing.GroupLayout(noEmployeePanel);
        noEmployeePanel.setLayout(noEmployeePanelLayout);
        noEmployeePanelLayout.setHorizontalGroup(
            noEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noEmployeeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noEmployeeConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noEmployeePanelLayout.setVerticalGroup(
            noEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noEmployeeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noEmployeeConfirmButton))
        );

        javax.swing.GroupLayout tardinessNoEmployeeLayout = new javax.swing.GroupLayout(tardinessNoEmployee.getContentPane());
        tardinessNoEmployee.getContentPane().setLayout(tardinessNoEmployeeLayout);
        tardinessNoEmployeeLayout.setHorizontalGroup(
            tardinessNoEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessNoEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tardinessNoEmployeeLayout.setVerticalGroup(
            tardinessNoEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tardinessNoEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        addEmployeeSuccessPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Success", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        addEmployeeSuccessText.setText("You have successfully added a new employee.");

        addEmployeeSuccessButton.setText("Continue");
        addEmployeeSuccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeSuccessButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addEmployeeSuccessPanelLayout = new javax.swing.GroupLayout(addEmployeeSuccessPanel);
        addEmployeeSuccessPanel.setLayout(addEmployeeSuccessPanelLayout);
        addEmployeeSuccessPanelLayout.setHorizontalGroup(
            addEmployeeSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addEmployeeSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeeSuccessPanelLayout.createSequentialGroup()
                        .addComponent(addEmployeeSuccessText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addEmployeeSuccessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        addEmployeeSuccessPanelLayout.setVerticalGroup(
            addEmployeeSuccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeSuccessText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addEmployeeSuccessButton))
        );

        javax.swing.GroupLayout addEmployeeSuccessLayout = new javax.swing.GroupLayout(addEmployeeSuccess.getContentPane());
        addEmployeeSuccess.getContentPane().setLayout(addEmployeeSuccessLayout);
        addEmployeeSuccessLayout.setHorizontalGroup(
            addEmployeeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeSuccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addEmployeeSuccessLayout.setVerticalGroup(
            addEmployeeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeSuccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToggleButton1.setText("jToggleButton1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Help Page", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Add Employee");

        jLabel4.setText("IDs may not be repeated, and you will recieve an error");

        jLabel3.setText("name and an unique 6-digit ID into the system. The");

        jLabel2.setText("Add an employee into the system. Enter the employee's");

        jLabel5.setText("if a repeated ID was entered.");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Remove Employee");

        jLabel7.setText("Enter an employee's name and ID into the text boxes");

        jLabel8.setText("to remove them from the system.");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Remove Employee");

        jLabel10.setText("Enter an employee's name and ID in the the text boxes");

        jLabel11.setText("to check their In and Out times, tardiness today and ");

        jLabel12.setText("time spent at work.");

        helpPageDone.setText("Back");
        helpPageDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpPageDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(helpPageDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpPageDone))
        );

        javax.swing.GroupLayout helpPageLayout = new javax.swing.GroupLayout(helpPage.getContentPane());
        helpPage.getContentPane().setLayout(helpPageLayout);
        helpPageLayout.setHorizontalGroup(
            helpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        helpPageLayout.setVerticalGroup(
            helpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        newEmployeeButton.setText("New Employee");
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setText("Remove Employee");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        checkTardinessButton.setForeground(new java.awt.Color(0, 0, 255));
        checkTardinessButton.setText("Check Tardiness");
        checkTardinessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTardinessButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(checkTardinessButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTardinessButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newEmployeeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmployeeNameFieldActionPerformed

    private void newEmployeeIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmployeeIDFieldActionPerformed

    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        newEmployeeMenu.pack();
        newEmployeeMenu.setVisible(true);
    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    private void newEmployeeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeBackActionPerformed
        newEmployeeMenu.setVisible(false);
    }//GEN-LAST:event_newEmployeeBackActionPerformed

    private void newEmployeeContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeContinueActionPerformed
        FileData fd = new FileData();
        String outputPath = fd.getFolder() + newEmployeeNameField.getText() + "_"
                + newEmployeeIDField.getText();
        /*
        Checks only for ID clashes, as multiple employees might have the same
        name, but unique IDs can be assigned to them.
        */
        if (!fd.employeeExists(newEmployeeIDField.getText())){

            try {

                fd.writeEmployeeDetails(outputPath, newEmployeeIDField.getText(), 
                        newEmployeeNameField.getText());

            } catch (IOException e) {

                showMessage("IO Error!");
            }

            addEmployeeSuccess.pack();
            addEmployeeSuccess.setVisible(true);
            newEmployeeNameField.setText(null);
            newEmployeeIDField.setText(null);

        } else {

            showMessage("This combination of employee Name and ID already"
                    + " exists! Please assign another unique ID if"
                    + " multiple employees have the same name!");

            newEmployeeNameField.setText(null);
            newEmployeeIDField.setText(null);
        }
    }//GEN-LAST:event_newEmployeeContinueActionPerformed

    private void checkTardinessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTardinessButtonActionPerformed
        tardinessMenu.pack();
        tardinessMenu.setVisible(true);
    }//GEN-LAST:event_checkTardinessButtonActionPerformed

    private void removeEmployeeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeBackActionPerformed
        removeEmployeeMenu.setVisible(false);
    }//GEN-LAST:event_removeEmployeeBackActionPerformed

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeButtonActionPerformed
        removeEmployeeMenu.pack();
        removeEmployeeMenu.setVisible(true);
    }//GEN-LAST:event_removeEmployeeButtonActionPerformed

    private void removeEmployeeContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeContinueActionPerformed

        removeEmployeeWarning.pack();
        removeEmployeeWarning.setVisible(true);
    }//GEN-LAST:event_removeEmployeeContinueActionPerformed

    private void warningBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningBackButtonActionPerformed
        removeEmployeeWarning.setVisible(false);
    }//GEN-LAST:event_warningBackButtonActionPerformed

    private void warningContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningContinueButtonActionPerformed
        FileData fd = new FileData();
        try {

            if (fd.delEmployee(fd.getFolder() + removeEmployeeNameField.getText() + "_"
                    + removeEmployeeIDField.getText()) == true) {
                removeEmployeeSuccess.pack();
                removeEmployeeSuccess.setVisible(true);
                removeEmployeeWarning.setVisible(false);
                removeEmployeeNameField.setText(null);
                removeEmployeeIDField.setText(null);
            } else {

                removeEmployeeWarning.setVisible(false);
                removeEmployeeSuccess.setVisible(false);
                removeEmployeeNameField.setText(null);
                removeEmployeeIDField.setText(null);
            }
        } catch (FileNotFoundException e) {
            showMessage("This employee does not exist! Make sure you had entered "
                    + "his/her name and ID correctly!");
        }

    }//GEN-LAST:event_warningContinueButtonActionPerformed

    private void removeFinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFinishButtonActionPerformed
        removeEmployeeSuccess.setVisible(false);
    }//GEN-LAST:event_removeFinishButtonActionPerformed

    private void employeeTardinessNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTardinessNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTardinessNameFieldActionPerformed

    private void employeeTardinessBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTardinessBackActionPerformed
        tardinessMenu.setVisible(false);
        employeeTardinessNameField.setText(null);
    }//GEN-LAST:event_employeeTardinessBackActionPerformed
    
    /*
    Displays the in and out times of an employee as for today, and also displays
    how late they are today compared to the predetermined login time
    */
    private void employeeTardinessContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTardinessContinueActionPerformed

        FileData fd = new FileData();
        String timeStamp = new SimpleDateFormat("yyyy/MM/dd").format(new Date());
        String inTimeFinal = "";
        String outTimeFinal = "";
        TimeManager tm = new TimeManager();

        try {
            File f = new File(fd.getFolder() + employeeTardinessNameField.getText() + "_"
                    + employeeTardinessIDField.getText());
            BufferedReader b = new BufferedReader(new FileReader(f));
            String readLine = "";
            while ((readLine = b.readLine()) != null) {

                if (readLine.contains(timeStamp) && readLine.contains("in")) {

                    String inTime = readLine.substring(0, readLine.length() - 14);
                    loginTime.setText(inTime);
                    inTimeFinal = inTime;
                    break;
                } else {
                    loginTime.setText("No login yet.");
                }
            }

            while ((readLine = b.readLine()) != null) {

                if (readLine.contains(timeStamp) && readLine.contains("out")) {

                    String outTime = readLine.substring(0, readLine.length() - 15);
                    logoutTime.setText(outTime);
                    outTimeFinal = outTime;
                    break;
                    
                } else {
                    
                    logoutTime.setText("No logout yet.");
                }
            }

            try {
                
                if(!loginTime.getText().equals("No login yet.") &&
                        !logoutTime.getText().equals("No logout yet.")){
                    
                tardinessTodayTime.setText(tm.calcDiff(tm.getLoginTime(), inTimeFinal));
                totalTime.setText(tm.calcDiff(inTimeFinal, outTimeFinal));
                tardinessDisplay.pack();
                tardinessDisplay.setVisible(true);
                
                } else if (logoutTime.getText().equals("No logout yet.")){
                    
                    tardinessTodayTime.setText(tm.calcDiff(tm.getLoginTime(), inTimeFinal));
                    
                } else if (loginTime.getText().equals("No login yet.")) {
                    
                    showMessage("This employee has not signed in today!");
                    tardinessTodayTime.setText("Error! No login!");
                    
                }

            } catch (Exception ex) {
                tardinessDisplay.setVisible(false);
                employeeTardinessNameField.setText(null);
                employeeTardinessIDField.setText(null);
                ex.printStackTrace();
            }
        } catch (FileNotFoundException e) {
            tardinessDisplay.setVisible(false);
            employeeTardinessNameField.setText(null);
            employeeTardinessIDField.setText(null);
            showMessage("This employee does not exist! Make sure you have entered "
                    + "both the name and ID correctly");

        } catch (IOException e) {
            tardinessDisplay.setVisible(false);
            employeeTardinessNameField.setText(null);
            employeeTardinessIDField.setText(null);
            showMessage("No such directory!");

        }


    }//GEN-LAST:event_employeeTardinessContinueActionPerformed

    private void tardinessDisplayDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tardinessDisplayDoneActionPerformed
        tardinessDisplay.setVisible(false);
        employeeTardinessNameField.setText(null);
        employeeTardinessIDField.setText(null);
    }//GEN-LAST:event_tardinessDisplayDoneActionPerformed

    private void noEmployeeConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noEmployeeConfirmButtonActionPerformed
        tardinessNoEmployee.setVisible(false);
    }//GEN-LAST:event_noEmployeeConfirmButtonActionPerformed

    private void addEmployeeSuccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeSuccessButtonActionPerformed
        addEmployeeSuccess.setVisible(false);
    }//GEN-LAST:event_addEmployeeSuccessButtonActionPerformed

    private void employeeTardinessIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTardinessIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTardinessIDFieldActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        helpPage.pack();
        helpPage.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void helpPageDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpPageDoneActionPerformed
        helpPage.setVisible(false);
    }//GEN-LAST:event_helpPageDoneActionPerformed

    private void showMessage(String text) {
        JOptionPane.showMessageDialog(null, text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeTardinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeTardinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeTardinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeTardinessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new employeeTardinessGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addEmployeeSuccess;
    private javax.swing.JButton addEmployeeSuccessButton;
    private javax.swing.JPanel addEmployeeSuccessPanel;
    private javax.swing.JLabel addEmployeeSuccessText;
    private javax.swing.JButton checkTardinessButton;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JLabel employeePositionLabel;
    private javax.swing.JButton employeeTardinessBack;
    private javax.swing.JButton employeeTardinessContinue;
    private javax.swing.JLabel employeeTardinessID;
    private javax.swing.JTextField employeeTardinessIDField;
    private javax.swing.JPanel employeeTardinessMenu;
    private javax.swing.JLabel employeeTardinessName;
    private javax.swing.JTextField employeeTardinessNameField;
    private javax.swing.JButton helpButton;
    private javax.swing.JFrame helpPage;
    private javax.swing.JButton helpPageDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel loginText;
    private javax.swing.JLabel loginTime;
    private javax.swing.JLabel logoutText;
    private javax.swing.JLabel logoutTime;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton newEmployeeBack;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JButton newEmployeeContinue;
    private javax.swing.JTextField newEmployeeIDField;
    private javax.swing.JFrame newEmployeeMenu;
    private javax.swing.JTextField newEmployeeNameField;
    private javax.swing.JPanel newEmployeePanel;
    private javax.swing.JButton noEmployeeConfirmButton;
    private javax.swing.JPanel noEmployeePanel;
    private javax.swing.JLabel noEmployeeText;
    private javax.swing.JButton removeEmployeeBack;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton removeEmployeeContinue;
    private javax.swing.JTextField removeEmployeeIDField;
    private javax.swing.JLabel removeEmployeeIDLabel;
    private javax.swing.JFrame removeEmployeeMenu;
    private javax.swing.JTextField removeEmployeeNameField;
    private javax.swing.JLabel removeEmployeeNameLabel;
    private javax.swing.JPanel removeEmployeePanel;
    private javax.swing.JFrame removeEmployeeSuccess;
    private javax.swing.JFrame removeEmployeeWarning;
    private javax.swing.JButton removeFinishButton;
    private javax.swing.JPanel removeSuccessPanel;
    private javax.swing.JLabel removeSuccessText;
    private javax.swing.JPanel removeWarningPanel;
    private javax.swing.JFrame tardinessDisplay;
    private javax.swing.JButton tardinessDisplayDone;
    private javax.swing.JPanel tardinessDisplayPanel;
    private javax.swing.JFrame tardinessMenu;
    private javax.swing.JFrame tardinessNoEmployee;
    private javax.swing.JLabel tardinessTodayText;
    private javax.swing.JLabel tardinessTodayTime;
    private javax.swing.JLabel timeAtWorkLabel;
    private javax.swing.JLabel totalTime;
    private javax.swing.JButton warningBackButton;
    private javax.swing.JButton warningContinueButton;
    private javax.swing.JLabel warningText1;
    private javax.swing.JLabel warningText2;
    // End of variables declaration//GEN-END:variables

}
